language: ruby
rvm:
  - ruby-1.9.3
env:
  - POSTGIS_VERSION=2.0.3
install:
  - sudo apt-get update
  - sudo sudo apt-add-repository -y ppa:sharpie/for-science;
  - sudo apt-get install postgresql-9.2-postgis -q
before_script:
  - sh -c 'sudo find / -name postgis.control'
  - psql -c 'create database world_cache_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres
script: rspec spec
