language: ruby
rvm:
  - ruby-1.9.3
env:
  - POSTGIS_VERSION=2.0.3 GEOS_VERSION=3.3.8
install:
  - sudo apt-get update
  - sudo sudo apt-add-repository -y ppa:sharpie/for-science;
  - sudo apt-get install postgresql-9.1-postgis -q
before_script:
  - psql -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -c 'create database world_cache_test;' -U postgres
script: rspec spec
