language: ruby
rvm:
  - ruby-1.9.3
env:
  - POSTGIS_VERSION=2.0.3
install:
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository ppa:sharpie/for-science -q
  - sudo apt-add-repository ppa:sharpie/postgis-stable -q
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -q
  - sudo apt-get update
  - sudo apt-get install postgresql-9.1-postgis2 -q
  - sudo find / -name postgis.control
before_script:
  - psql -c 'create database world_cache_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres
script: rspec spec
