development:
  adapter: postgis
  encoding: unicode
  database: world_cache
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: brandonwilburn
  password:  

test:
  adapter: postgis
  encoding: unicode
  database: world_cache
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: brandonwilburn
  password:  

production:
  adapter: postgis
  encoding: unicode
  database: world_cache 
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: brandonwilburn
  password:  

