development:
  adapter: postgis
  encoding: unicode
  database: world_cache_development
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: postgres
  password:  

test:
  adapter: postgis
  encoding: unicode
  database: world_cache_test
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: postgres
  password:  

production:
  adapter: postgis
  encoding: unicode
  database: world_cache_production 
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: postgres
  password:  

